# Generated by Django 3.0.2 on 2020-01-26 09:01

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('program_id', models.IntegerField()),
                ('KKS', models.CharField(max_length=20)),
                ('name', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('deatils', models.TextField()),
                ('program_type', models.CharField(max_length=20)),
                ('block', models.IntegerField()),
                ('in_current_status', models.IntegerField(default=0)),
                ('modified_by', models.ForeignKey(default=1, on_delete=models.SET('Deleted'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
