# Generated by Django 3.0.2 on 2020-01-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='deatils',
            new_name='details',
        ),
    ]
